/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Messenger_H
#define Messenger_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "service_types.h"

namespace MessengerNamespace {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class MessengerIf {
 public:
  virtual ~MessengerIf() {}
  virtual void sendMessage(std::string& _return, const std::string& text) = 0;
};

class MessengerIfFactory {
 public:
  typedef MessengerIf Handler;

  virtual ~MessengerIfFactory() {}

  virtual MessengerIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(MessengerIf* /* handler */) = 0;
  };

class MessengerIfSingletonFactory : virtual public MessengerIfFactory {
 public:
  MessengerIfSingletonFactory(const ::std::shared_ptr<MessengerIf>& iface) : iface_(iface) {}
  virtual ~MessengerIfSingletonFactory() {}

  virtual MessengerIf* getHandler(const ::apache::thrift::TConnectionInfo&) override {
    return iface_.get();
  }
  virtual void releaseHandler(MessengerIf* /* handler */) override {}

 protected:
  ::std::shared_ptr<MessengerIf> iface_;
};

class MessengerNull : virtual public MessengerIf {
 public:
  virtual ~MessengerNull() {}
  void sendMessage(std::string& /* _return */, const std::string& /* text */) override {
    return;
  }
};

typedef struct _Messenger_sendMessage_args__isset {
  _Messenger_sendMessage_args__isset() : text(false) {}
  bool text :1;
} _Messenger_sendMessage_args__isset;

class Messenger_sendMessage_args {
 public:

  Messenger_sendMessage_args(const Messenger_sendMessage_args&);
  Messenger_sendMessage_args& operator=(const Messenger_sendMessage_args&);
  Messenger_sendMessage_args() noexcept
                             : text() {
  }

  virtual ~Messenger_sendMessage_args() noexcept;
  std::string text;

  _Messenger_sendMessage_args__isset __isset;

  void __set_text(const std::string& val);

  bool operator == (const Messenger_sendMessage_args & rhs) const
  {
    if (!(text == rhs.text))
      return false;
    return true;
  }
  bool operator != (const Messenger_sendMessage_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Messenger_sendMessage_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Messenger_sendMessage_pargs {
 public:


  virtual ~Messenger_sendMessage_pargs() noexcept;
  const std::string* text;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Messenger_sendMessage_result__isset {
  _Messenger_sendMessage_result__isset() : success(false) {}
  bool success :1;
} _Messenger_sendMessage_result__isset;

class Messenger_sendMessage_result {
 public:

  Messenger_sendMessage_result(const Messenger_sendMessage_result&);
  Messenger_sendMessage_result& operator=(const Messenger_sendMessage_result&);
  Messenger_sendMessage_result() noexcept
                               : success() {
  }

  virtual ~Messenger_sendMessage_result() noexcept;
  std::string success;

  _Messenger_sendMessage_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const Messenger_sendMessage_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Messenger_sendMessage_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Messenger_sendMessage_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Messenger_sendMessage_presult__isset {
  _Messenger_sendMessage_presult__isset() : success(false) {}
  bool success :1;
} _Messenger_sendMessage_presult__isset;

class Messenger_sendMessage_presult {
 public:


  virtual ~Messenger_sendMessage_presult() noexcept;
  std::string* success;

  _Messenger_sendMessage_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class MessengerClient : virtual public MessengerIf {
 public:
  MessengerClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  MessengerClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void sendMessage(std::string& _return, const std::string& text) override;
  void send_sendMessage(const std::string& text);
  void recv_sendMessage(std::string& _return);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class MessengerProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<MessengerIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) override;
 private:
  typedef  void (MessengerProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_sendMessage(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  MessengerProcessor(::std::shared_ptr<MessengerIf> iface) :
    iface_(iface) {
    processMap_["sendMessage"] = &MessengerProcessor::process_sendMessage;
  }

  virtual ~MessengerProcessor() {}
};

class MessengerProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  MessengerProcessorFactory(const ::std::shared_ptr< MessengerIfFactory >& handlerFactory) noexcept :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) override;

 protected:
  ::std::shared_ptr< MessengerIfFactory > handlerFactory_;
};

class MessengerMultiface : virtual public MessengerIf {
 public:
  MessengerMultiface(std::vector<std::shared_ptr<MessengerIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~MessengerMultiface() {}
 protected:
  std::vector<std::shared_ptr<MessengerIf> > ifaces_;
  MessengerMultiface() {}
  void add(::std::shared_ptr<MessengerIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void sendMessage(std::string& _return, const std::string& text) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->sendMessage(_return, text);
    }
    ifaces_[i]->sendMessage(_return, text);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class MessengerConcurrentClient : virtual public MessengerIf {
 public:
  MessengerConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  MessengerConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void sendMessage(std::string& _return, const std::string& text) override;
  int32_t send_sendMessage(const std::string& text);
  void recv_sendMessage(std::string& _return, const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
